// Generated by eXtraCoffeeScript 1.3.1
(function() {
  var parser, uglify, _ref;

  _ref = require('uglify-js'), parser = _ref.parser, uglify = _ref.uglify;

  exports.minify = function(code, opt) {
    var ast, _ref1;
    if (!opt || opt === true) {
      return uglify.split_lines(uglify.gen_code(uglify.ast_squeeze(uglify.ast_mangle(parser.parse(code))), {
        ascii_only: true,
        inline_script: true
      }), 32768);
    } else {
      if (opt.max_line_length == null) {
        opt.max_line_length = (_ref1 = opt.max_line_len) != null ? _ref1 : 32768;
      }
      opt.lift_variables = opt.lift_variables || opt.lift_vars || false;
      if (opt.ascii_only == null) {
        opt.ascii_only = !opt.allow_non_ascii;
      }
      if (opt.inline_script == null) {
        opt.inline_script = true;
      }
      ast = parser.parse(code, opt.strict_semicolons);
      if (opt.lift_variables) {
        ast = uglify.ast_lift_variables(ast);
      }
      if (!opt.no_mangle) {
        ast = uglify.ast_mangle(ast, opt);
      }
      if (!opt.no_squeeze) {
        ast = uglify.ast_squeeze(ast, opt);
      }
      ast = uglify.gen_code(ast, opt);
      if (opt.max_line_length > 0) {
        ast = uglify.split_lines(ast, opt.max_line_length);
      }
      return ast;
    }
  };

}).call(this);
